trigger:
- refs/heads/*
- refs/pull/*/merge

pool:
  vmImage: 'macOS-10.14'

variables:
  scheme: 'Injector'
  sdk: 'macosx'
  configuration: 'Release'

steps:
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false
